<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Student;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $users = User::with(['student', 'teacher'])->orderBy('role')->paginate(20);
        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'        => 'required|string|max:255',
            'email'       => 'required|email|unique:users,email',
            'password'    => 'required|string|min:8|confirmed',
            'role'        => 'required|in:admin,teacher,student',
            'employee_id' => 'required_if:role,teacher|nullable|string|unique:teachers,employee_id',
            'student_id'  => 'required_if:role,student|nullable|string|unique:students,student_id',
            'grade_level' => 'nullable|string|max:50',
            'section'     => 'nullable|string|max:50',
            'department'  => 'nullable|string|max:100',
        ]);

        $user = User::create([
            'name'     => $request->name,
            'email'    => $request->email,
            'password' => Hash::make($request->password),
            'role'     => $request->role,
        ]);

        // Create role-specific profile
        if ($request->role === 'student') {
            $student = Student::create([
                'user_id'     => $user->id,
                'student_id'  => $request->student_id,
                'grade_level' => $request->grade_level,
                'section'     => $request->section,
                // qr_token auto-generated by Student::creating() model event
            ]);
        } elseif ($request->role === 'teacher') {
            Teacher::create([
                'user_id'     => $user->id,
                'employee_id' => $request->employee_id,
                'department'  => $request->department,
            ]);
        }

        $redirect = redirect()->route('admin.users.index')
            ->with('success', "{$user->name} account created successfully.");

        // For students: flash QR data so the modal auto-opens on redirect
        if ($request->role === 'student' && isset($student)) {
            $redirect->with('new_student_qr', [
                'name'        => $user->name,
                'student_id'  => $student->student_id,
                'grade_level' => $student->grade_level,
                'section'     => $student->section,
                'qr_url'      => $student->qrUrl(),
            ]);
        }

        return $redirect;
    }

    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'        => 'required|string|max:255',
            'email'       => 'required|email|unique:users,email,' . $user->id,
            'password'    => 'nullable|string|min:8|confirmed',
            'student_id'  => 'nullable|string|unique:students,student_id,' . ($user->student?->id ?? 'NULL') . ',id',
            'grade_level' => 'nullable|string|max:50',
            'section'     => 'nullable|string|max:50',
            'employee_id' => 'nullable|string|unique:teachers,employee_id,' . ($user->teacher?->id ?? 'NULL') . ',id',
            'department'  => 'nullable|string|max:100',
        ]);

        $user->name  = $request->name;
        $user->email = $request->email;

        if ($request->filled('password')) {
            $user->password = Hash::make($request->password);
        }

        $user->save();

        // Update role-specific profile if exists
        if ($user->role === 'student' && $user->student) {
            $user->student->update([
                'student_id'  => $request->student_id  ?? $user->student->student_id,
                'grade_level' => $request->grade_level,
                'section'     => $request->section,
            ]);
        } elseif ($user->role === 'teacher' && $user->teacher) {
            $user->teacher->update([
                'employee_id' => $request->employee_id ?? $user->teacher->employee_id,
                'department'  => $request->department,
            ]);
        }

        if ($request->wantsJson() || $request->ajax()) {
            return response()->json(['success' => true, 'message' => 'User updated successfully.']);
        }

        return redirect()->route('admin.users.index')
            ->with('success', 'User updated successfully.');
    }

    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.users.index')
            ->with('success', 'User removed.');
    }
}
